_format_version: "3.0"
_transform: true

services:
  - name: user-service
    url: http://localhost:8080/users
    host:
      docker:
        for:
          mac:
            localhost:
    routes:
      - name: user-route
        paths:
          - /api/v1/users
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        protocols:
          - http
