version: "3.9"

services:
  application:
    restart: always
    networks:
      - kong-net
    container_name: user-service
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  kong:
    restart: always
    networks:
      - kong-net
    image: kong
    volumes:
      - "./config:/usr/local/kong/declarative"
    container_name: kong-gateway
    environment:
      - KONG_DATABASE= off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_LOG_LEVEL=debug
      - KONG_PLUGINS=bundled
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

networks:
  kong-net:
    external: true
